### ISSUE TITLE
UI Redesign: 优化界面风格 - 青绿渐变主题

### ISSUE THREAD

**Issue by PerfectQing** [PerfectQing/PerfectQing.github.io#1]
## 优化目标
对网站界面进行视觉优化，主要关注以下几个方面：

### 色彩方案
- 采用青绿色系渐变作为主色调
- 建议使用的色值范围:
  - 主要青色: `#00C9A7` → `#017C67`
  - 辅助绿色: `#4CAF50` → `#2E7D32`
  - 确保色彩过渡自然舒适

### 界面现代化
1. **导航栏优化**
   - 添加半透明效果
   - 优化按钮hover状态的动画效果
   - 考虑使用毛玻璃效果(backdrop-filter)

2. **卡片样式**
   - 增加圆角设计
   - 添加适当的阴影效果
   - hover时的轻微浮起效果

3. **字体排版**
   - 使用更现代的字体组合
   - 优化标题和正文的层级关系
   - 确保中英文字体搭配协调

4. **动效设计**
   - 页面切换时添加平滑过渡效果
   - 滚动时的视差效果
   - 适当的微动效

### 保留功能
- 确保所有现有功能完整保留
- 不改变网站的基本结构和导航逻辑
- 维持现有的响应式设计

## 技术实现建议
```css
/* 示例：主要渐变效果 */
.gradient-bg {
  background: linear-gradient(135deg, #00C9A7 0%, #017C67 100%);
}

/* 示例：卡片样式 */
.card {
  border-radius: 16px;
  background: rgba(255, 255, 255, 0.95);
  box-shadow: 0 8px 32px rgba(0, 201, 167, 0.1);
  transition: transform 0.3s ease;
}

.card:hover {
  transform: translateY(-5px);
}

/* 示例：导航栏毛玻璃效果 */
.navbar {
  background: rgba(255, 255, 255, 0.8);
  backdrop-filter: blur(10px);
  -webkit-backdrop-filter: blur(10px);
}
```

## 注意事项
1. 确保配色符合 WCAG 2.1 无障碍标准
2. 测试不同设备和浏览器的兼容性
3. 优化页面加载性能
4. 保持代码的可维护性
